---
- name: Provision backend
  hosts: all
  vars:
    - ansible_become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        name:
          - nginx
          - postgresql
          - libssl-dev
          - gnupg2
          # Required for ansible
          - acl
          - python3-psycopg2

    - name: Install key
      ansible.builtin.apt_key:
        state: present
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    - name: node repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_18.x bullseye main"
    - name: Install node
      ansible.builtin.apt:
        state: latest
        name: nodejs
    - name: Install yarn
      ansible.builtin.command:
        cmd: "npm install -g yarn"

    - name: Check for rustup
      ansible.builtin.stat:
        path: "/tmp/rustup.sh"
      register: rustup_file
    - name: Download rustup
      become_user: vagrant
      ansible.builtin.shell:
        cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh"
      when: not rustup_file.stat.exists
    - name: Execute installer
      become_user: vagrant
      ansible.builtin.shell:
        cmd: "sh /tmp/rustup.sh -y"
      when: not rustup_file.stat.exists

    - name: Start postgres
      ansible.builtin.systemd:
        name: postgresql
        state: started
    - name: Create backend db user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ backend_db_user }}"
        password: "{{ backend_db_password }}"
    - name: Create backend database
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ backend_db_name }}"
        encoding: UTF-8
        owner: "{{ backend_db_user }}"

    - name: Create backend group
      ansible.builtin.group:
        name: backend
    - name: Create backend user
      ansible.builtin.user:
        name: backend
        system: yes
        group: backend

    - name: Create /etc/backend
      ansible.builtin.file:
        name: /etc/backend
        state: directory
        mode: 0750
        owner: root
        group: backend
    - name: Apply backend config.toml
      template:
        src: backend/config.toml.jinja2
        dest: /etc/backend/config.toml
        owner: root
        group: backend
        mode: 0640

    - name: Compile backend
      become_user: vagrant
      ansible.builtin.command:
        chdir: /vagrant/backend
        cmd: "/home/vagrant/.cargo/bin/cargo build -r -p backend"
    - name: Copy to /usr/local/bin
      copy:
        remote_src: yes
        src: /vagrant/backend/target/release/backend
        dest: /usr/local/bin/backend
        mode: 0755
        owner: root

    - name: Stop backend.service
      systemd:
        name: backend.service
        state: stopped
      ignore_errors: yes
    - name: Apply migrations
      command:
        chdir: /vagrant/backend
        cmd: /usr/local/bin/backend migrate migrations/

    - name: Install systemd service
      copy:
        src: backend/backend.service
        dest: /etc/systemd/system/backend.service
        owner: root
    - name: Restart backend
      systemd:
        enabled: yes
        name: backend.service
        state: restarted

    - name: Apply nginx template
      template:
        src: backend/backend.nginx.jinja2
        dest: /etc/nginx/sites-available/backend.conf
    - name: Link to enabled
      file:
        state: link
        owner: root
        group: root
        src: /etc/nginx/sites-available/backend.conf
        dest: /etc/nginx/sites-enabled/backend.conf
    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Restart backend
      systemd:
        name: backend.service
        state: restarted
